### ISSUE TITLE
Unable to create a Deal. Getting (Exception Value: Model instances passed to related filters must be saved.)

### ISSUE THREAD

**Issue by virendracis** [DjangoCRM/django-crm#5]
`Environment:

Request Method: GET
Request URL: http://127.0.0.1:8888/en/crm/crm/deal/add/

Django Version: 5.0.6
Python Version: 3.12.3
Installed Applications:
['django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'crm.apps.CrmConfig',
 'massmail.apps.MassmailConfig',
 'analytics.apps.AnalyticsConfig',
 'help',
 'tasks.apps.TasksConfig',
 'chat.apps.ChatConfig',
 'voip',
 'common.apps.CommonConfig',
 'settings']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'common.utils.usermiddleware.UserMiddleware']

Traceback (most recent call last):
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1872, in _changeform_view
    formsets, inline_instances = self._create_formsets(
                                 
  File "/mnt/Extras/RAW_DIAMOND/django-crm/crm/site/dealadmin.py", line 136, in _create_formsets
    p = Payment.objects.filter(deal=obj).last()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 147, in get_prep_lookup
    self.rhs = get_normalized_value(self.rhs, self.lhs)[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Extras/RAW_DIAMOND/django-crm/venv/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 45, in get_normalized_value
    raise ValueError("Model instances passed to related filters must be saved.")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: ValueError at /en/crm/crm/deal/add/
Exception Value: Model instances passed to related filters must be saved.
`

**Comment by DjangoCRM** [comment]
Hi, thanks for reporting.
I assume you are logged in to the CRM site as an administrator. Therefore, a button has become available to you that is not available to regular users.
Please use the button ADD REQUEST (DEAL).
But for the correct user interface, you will have to create a new user with the Sales Manager role and use it to log in.

**Comment by virendracis** [comment]
Thanks a lot @DjangoCRM
